force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TMM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Calculation_Updates__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Updates__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Calculation Updates</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Next_Birthday__c.field-meta.xml
<CustomField>
    <fullName>Next_Birthday__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Next Birthday</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TeamMemberProcessing.cls
public class TeamMemberProcessing implements Schedulable, Database.Batchable<Team_Member__c>
{
	public void execute(SchedulableContext ctx)
    {
        database.executeBatch(this, 100);
    }
    
    public Iterable<Team_Member__c> start(Database.BatchableContext ctx)
    {
        // this will capture all fields where calculations have not run or completed
        return 
            [
            	SELECT Id, Date_of_Birth__c, Next_Birthday__c, Calculation_Updates__c 
                FROM Team_Member__c 
                WHERE Calculation_Updates__c <: system.today()
            ];
    }
    
    public void execute(Database.BatchableContext ctx, List<Team_Member__c> items)
    {
        // this will effectively prod the Workflow Trigger to perform the re-calculation
        
        for(Team_Member__c item : items)
        {
            item.Calculation_Updates__c = system.today();
        }
        
        database.upsert(items);
    }
    
    public void finish(Database.BatchableContext ctx)
    {
        
    }
}