force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TMM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Age</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Age Range</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Calculation_Updates__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Updates__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Calculation Updates</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Forename__c.field-meta.xml
<CustomField>
    <fullName>Forename__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Forename</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Next_Birthday__c.field-meta.xml
<CustomField>
    <fullName>Next_Birthday__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Next Birthday</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TeamMemberProcessingTests.cls
@isTest
public class TeamMemberProcessingTests 
{
    @testSetup
    static void Setup()
    {
       Team_Member__c tm = new Team_Member__c
            (
                Date_of_Birth__c = Date.newInstance(1980, 01, 01),
                Calculation_Updates__c = system.today().addDays(-1),
                Forename__c = 'Bob',
                Surname__c = 'Smith'
            );
        
        insert tm;
    }
    
	@isTest
    static void TestUpdates()
    {
        test.startTest();
        
        database.executeBatch(new TeamMemberProcessing(), 100);
        
        test.stopTest();
        
        List<Team_Member__c> items = [SELECT Id, Date_of_Birth__c, Next_Birthday__c, Age__c, Age_Range__c, Calculation_Updates__c FROM Team_Member__c];
        
        Team_Member__c item = items.get(0);
        
        system.assertNotEquals(null, item.Next_Birthday__c);
        system.assertNotEquals(null, item.Age__c);
        system.assertNotEquals(null, item.Age_Range__c);
    }
    
    @isTest
    static void TestSort()
    {
        Team_Member__c tm = new Team_Member__c
            (
                Date_of_Birth__c = Date.newInstance(1980, 02, 02),
                Calculation_Updates__c = system.today().addDays(-1),
                Forename__c = 'Bob',
                Surname__c = 'Freddo'
            );
        
        insert tm;
        
        List<Team_Member__c> items = TeamMemberQueries.GetAllSortedBySurname();
        
        for(Team_Member__c item : items)
        {
        	system.debug(item.Surname__c);    
        }
        
        Team_Member__c freddo = items.get(0);
        Team_Member__c smith = items.get(1);
        
        system.assertEquals('Freddo', freddo.Surname__c);
        system.assertEquals('Smith', smith.Surname__c);
    }
}