force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TMM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Age</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Age_Range__c.field-meta.xml
<CustomField>
    <fullName>Age_Range__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Age Range</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Calculation_Updates__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Updates__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <encryptionScheme>None</encryptionScheme>
    <label>Calculation Updates</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Forename__c.field-meta.xml
<CustomField>
    <fullName>Forename__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Forename</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Next_Birthday__c.field-meta.xml
<CustomField>
    <fullName>Next_Birthday__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Next Birthday</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Surname__c.field-meta.xml
<CustomField>
    <fullName>Surname__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TeamMemberQueries.cls
public class TeamMemberQueries 
{
	public static List<Team_Member__c> GetAll()
    {
        return 
            [
                SELECT Id, Date_of_Birth__c, Next_Birthday__c, Age__c, Age_Range__c, Calculation_Updates__c, Forename__c, Surname__c
                FROM Team_Member__c
                WHERE Id != NULL
            ];
    }
    
    public static List<Team_Member__c> GetAllSortedBySurname()
    {
        List<Team_Member__c> items = new List<Team_Member__c>
            ([
                SELECT Id, Date_of_Birth__c, Next_Birthday__c, Age__c, Age_Range__c, Calculation_Updates__c, Forename__c, Surname__c
                FROM Team_Member__c
                WHERE Id != NULL
            ]);
        
        Collection.Sort(items, Team_Member__c.Surname__c);
        
        for(Team_Member__c item : items)
        {
        	system.debug(item.Surname__c);    
        }
        
        return items;
    }
}